## Oppgave 1 a)

In [1]:
import pandas as pd

inntekter = pd.Series({'Mons': 617, 'Nils': 836, 'Jens': 749, 'Hans': 583})

print(inntekter.iloc[2])
print(inntekter.iloc[[2]])

print('-' * 20)
print(inntekter.loc['Nils'])
print(inntekter.loc[['Nils']])

749
Jens    749
dtype: int64
--------------------
836
Nils    836
dtype: int64

## Oppgave 1 b)

In [2]:
print('Inntekter i stigende rekkefølge:')
print(inntekter.sort_values())

print('-' * 40)
print('Inntekter i synkende rekkefølge:')
print(inntekter.sort_values(ascending=False))

print('-' * 40)
print(f'Summen av inntektene er {inntekter.sum()},')
print(f'med et gjennomsnitt lik {inntekter.mean()}.')

Inntekter i stigende rekkefølge:
Hans    583
Mons    617
Jens    749
Nils    836
dtype: int64
----------------------------------------
Inntekter i synkende rekkefølge:
Nils    836
Jens    749
Mons    617
Hans    583
dtype: int64
----------------------------------------
Summen av inntektene er 2785,
med et gjennomsnitt lik 696.25.

## Oppgave 2 a)

In [3]:
data = {'Navn': ['Kari', 'Guri', 'Siri', 'Mari'],
        'Inntekt': [851, 907, 739, 821],
        'Formue': [2984, 1183, 4092, 1625]}

df = pd.DataFrame(data)
df.index = ['Person 1', 'Person 2', 'Person 3', 'person 4']

display(df.head(3))
display(df.tail(3))
display(df.iloc[[2]])
display(df.loc[['Person 3']])
display(df.loc[df['Navn'] == 'Siri'])

          Navn  Inntekt  Formue
Person 1  Kari      851    2984
Person 2  Guri      907    1183
Person 3  Siri      739    4092

          Navn  Inntekt  Formue
Person 2  Guri      907    1183
Person 3  Siri      739    4092
person 4  Mari      821    1625

          Navn  Inntekt  Formue
Person 3  Siri      739    4092

          Navn  Inntekt  Formue
Person 3  Siri      739    4092

          Navn  Inntekt  Formue
Person 3  Siri      739    4092

## Oppgave 2 b)

In [4]:
df_sortert = df.sort_values('Formue', ascending=False)
display(df_sortert)

df_filtrert = df.loc[(df['Inntekt'] > 800) & (df['Formue'] > 1500)]
display(df_filtrert)

          Navn  Inntekt  Formue
Person 3  Siri      739    4092
Person 1  Kari      851    2984
person 4  Mari      821    1625
Person 2  Guri      907    1183

          Navn  Inntekt  Formue
Person 1  Kari      851    2984
person 4  Mari      821    1625

## Oppgave 3

In [5]:
resultater = {'Volum': [1120, 1360, 1510, 1470, 1440],
              'Faste': [1.27, 1.35, 1.39, 1.44, 1.61]}
df = pd.DataFrame(resultater)
df.index = [2021, 2022, 2023, 2024, 2025]

db = 3000
skatt = 0.22

df['Res før skatt'] = db * df['Volum'] - 1e6 * df['Faste']
df['Skatt'] = skatt * df['Res før skatt']
df['Res etter skatt'] = df['Res før skatt'] - df['Skatt']
df

      Volum  Faste  Res før skatt     Skatt  Res etter skatt
2021   1120   1.27      2090000.0  459800.0        1630200.0
2022   1360   1.35      2730000.0  600600.0        2129400.0
2023   1510   1.39      3140000.0  690800.0        2449200.0
2024   1470   1.44      2970000.0  653400.0        2316600.0
2025   1440   1.61      2710000.0  596200.0        2113800.0